import 'package:firebase_core/firebase_core.dart';

class FirebaseConfig {
  // These values would normally be stored in a separate firebase_options.dart file generated by the Firebase CLI
  // For this example, they're placeholders - you should replace them with actual values
  static FirebaseOptions get platformOptions {
    // Replace these values with your actual Firebase project configuration
    return const FirebaseOptions(
      apiKey: 'YOUR_API_KEY',  // Replace with your API key
      appId: 'YOUR_APP_ID',    // Replace with your App ID
      messagingSenderId: 'YOUR_SENDER_ID', // Replace with your Sender ID
      projectId: 'YOUR_PROJECT_ID', // Replace with your Project ID
      authDomain: 'YOUR_AUTH_DOMAIN', // Replace with your Auth Domain
      storageBucket: 'YOUR_STORAGE_BUCKET', // Replace with your Storage Bucket
    );
  }
}

// Instructions to set up Firebase in your Flutter app:
// 1. Install the FlutterFire CLI: npm install -g firebase-tools
// 2. Log in to Firebase: firebase login
// 3. Configure your app: flutterfire configure
// 4. The above command will generate firebase_options.dart
// 5. Import and use the generated file instead of this placeholder 